CREATE TABLE IF NOT EXISTS public.contacts(
    contact_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    contact_firstname character varying NOT NULL,
    contact_lastname character varying NOT NULL,
    contact_email character varying NOT NULL,
    contact_phone character varying NOT NULL,
    contact_relationship character varying NOT NULL,
    contact_info text varying NOT NULL,
    contacted numeric(1, 0) NOT NULL,
    account_id integer not null

);

ALTER TABLE IF EXISTS public.contacts
    ADD CONSTRAINT fk_account
    FOREIGN KEY (account_id)
    REFERENCES public.account (account_id)
    MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

INSERT INTO contacts (contact_firstname,
                    contact_lastname,
					 contact_email,
					 contact_phone,
					 contact_relationship, contact_info, contacted, account_id)
Values('Anna', 'Taylor', 'taylor@fun.com', '2082068943', 'friend', 'super cool person who loves batman', 1, 2);
INSERT INTO contacts (contact_firstname,
                    contact_lastname,
					 contact_email,
					 contact_phone,
					 contact_relationship, contact_info, contacted, account_id)
Values('Zach', 'Taylor', 'taylortoaytay@fun.com', '2082040943', 'friend', 'nice person', 1, 2);